
language: node_js
node_js:
  - 6
  - 8
  - 10
cache: yarn
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
before_script:
  - yarn clean
  - yarn build
after_success:
  - yarn coverage
