
language: node_js
node_js:
  - 6
cache: yarn
services:
  - mysql
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y jq
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
before_script:
  - yarn install:peers
